### ISSUE TITLE
keyerror:

### ISSUE THREAD

**Issue by saravind2095** [akTwelve/cocosynth#11]
hie,
actually I'm new to object detection. can you please help me out from these errors
1. while viewing coco dataset
2. while loading train dataset
![Capture1](https://user-images.githubusercontent.com/45196703/63635686-d1d5ab00-c682-11e9-8c31-d63cccb210da.PNG)
![Capture3](https://user-images.githubusercontent.com/45196703/63635687-d26e4180-c682-11e9-986b-9b2a46075c45.PNG)

Thank you.

**Comment by saravind2095** [comment]
here my subcategory and category is 1

**Comment by akTwelve** [comment]
My apologies, @saravind2095, I completely missed this question. If you're still stuck, I'll try to help. It seems like maybe your coco_instances.json is not right. Can you share the parts related to image 8? (i.e. the json for image definition, segmentations)

**Comment by saravind2095** [comment]
yeah, i found that prblm n solved it. but here I'm using google cloud platform to build this model. at the end of the work I'm trying to visualize the video output but unfortunately the kernel was stopped n it seems died!!....

please, help me here to find a solution for this problem! and my question is?
how to visualize the results of video and webcam using GCP or any cloud services??

**Comment by saravind2095** [comment]
live streaming?

**Comment by akTwelve** [comment]
Unfortunately I don’t have any experience with running on cloud services.
