### ISSUE TITLE
Error in section: Create the Training and Validation Datasets

### ISSUE THREAD

**Issue by HenriqueLeal** [akTwelve/cocosynth#20]
Good night, first congratulations on the work. I was following the tutorial that taught how to train MaskR CNN with my own dataset, I did all the previous steps, generated the images with "image_composition.py", changed the number of classes and dimensions of the images in the model.

However, in the Create the Training and Validation Datasets section, the code is giving the following error: 

"KeyError Traceback (most recent call last)
<ipython-input-9-5b68485bc6aa> in <module>
      1 dataset_train = CocoLikeDataset ()
      2 dataset_train.load_data ('../ datasets / box_dataset_synthetic / train / coco_instances.json',
----> 3 '../datasets/box_dataset_synthetic/train/images')
      4 dataset_train.prepare ()
      5

<ipython-input-6-5aee722e418a> in load_data (self, annotation_json, images_dir)
     49
     50 image_path = os.path.abspath (os.path.join (images_dir, image_file_name))
---> 51 image_annotations = annotations [image_id]
     52
     53 # Add the image using the base method from utils.Dataset

KeyError: 654 "

detail: the name of the dataset is correct, I changed it to the same name as yours.

When I put your coco_instances.json it works, but in mine it doesn't work, I compared both and I couldn't detect differences.

Can you please help me?

Thank you very much

**Comment by borgarpa** [comment]
Check whether you have masks with no visible objects. For me it was causing the creation of more images in the `'image'` key of `coco_instances.json` than annotations, hence the `KeyError`.
