### ISSUE TITLE
[Help Wanted] Display Keypoints

### ISSUE THREAD

**Issue by FelipeR2U** [akTwelve/cocosynth#7]
Is there a way to extend the Coco_Image_Viewer with a function to display keypoints?

**Comment by akTwelve** [comment]
It's definitely possible. The SVG would be pretty similar to creating the polygons that are already there.

**Comment by saravind2095** [comment]
hey hi, i had a problem with COCO Instances JSON (coco_json_utils.py) when im creating a json file. i got these error AttributeError: 'MultiPolygon' object has no attribute 'exterior' .
can you please help me with these?

**Comment by akTwelve** [comment]
I may come back to this at some point, but I just don't have the time to do it right now. It's a good suggestion though.
