### ISSUE TITLE
AttributeError: 'MultiPolygon' object has no attribute 'exterior' .

### ISSUE THREAD

**Issue by saravind2095** [akTwelve/cocosynth#9]
hey hi, i had a problem with COCO Instances JSON (coco_json_utils.py) while i'm creating a json file i got these error AttributeError: 'MultiPolygon' object has no attribute 'exterior' .
can you please help me with this?
![Capture](https://user-images.githubusercontent.com/45196703/63488472-b163f000-c4cc-11e9-8b29-1181aef4926b.PNG)
?

**Comment by akTwelve** [comment]
This happens when you have a mask that is split into multiple pieces instead of just one. A few people have had this problem so I'm going to look into at least adding a more helpful error message. For now, just remove image 104 from your list and it should work.

**Comment by akTwelve** [comment]
Ok, I'm having a really hard time trying to reproduce this error. Can you share the image that is causing the problem?

**Comment by akTwelve** [comment]
I have a fix for this now, it's in this branch. https://github.com/akTwelve/cocosynth/tree/bugfix/multipolygon_error

Can you try it out and let me know if it works?

**Comment by saravind2095** [comment]
hey hie,

thank you for your response . it works....

**Comment by akTwelve** [comment]
Thanks for verifying, @saravind2095, I've pulled the fix into master. 🙂

**Comment by rbavery** [comment]
I think this fix would not work in cases where we need to label instances with gaps in them: https://github.com/akTwelve/cocosynth/pull/10/files

This simplifies the polygon such that it fills in those gaps when recording the pixel coordinates in the COCO dataset.
